### ISSUE TITLE
'More info...'  404 error

### ISSUE THREAD

**Issue by martywd** [kierun/ttrss-ui-libravatar#1]
Install 'ui_libravatar' plugin into 'plugins.local' and then go to tt-rss' 'Preferences|Plugins' in a browser.

Currently, clicking on the 'ui_libravatar' **'More info...'** button sends one to:

==>   https://git.tt-rss.org/kierun/ttrss-ui-libravatar

 yielding a '404' error.

.

**Comment by kierun** [comment]
Thank you for reporting.

Fixed in `63a809312`.

**Comment by kierun** [comment]
Actually fixed in `e498e5318f` because I am dumb and forgot to delete things…
